sudo: required
services: 
  - docker

before_install:
  - docker build -t docker-playground -f Dockerfile.dev .

script:
  - docker run docker-playground npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-playground"
  env: "Dockerplayground-env"
  bucket_name: "elasticbeanstalk-us-east-2-516128361868"
  bucket_path: "docker-playground"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"